/* USERS CONSTANTS */
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER';

/* DEBATE CONSTANTS */
export const FETCHING_DEBATE = 'FETCH_DEBATE';
export const FETCHING_DEBATE_SUCCESS = 'FETCH_DEBATE_SUCCESS';
export const FETCHING_DEBATE_ERROR = 'FETCH_DEBATE_ERROR';

/* RESPONSES CONSTANTS */
export const FETCHING_RESPONSE = 'FETCHING_RESPONSE';
export const FETCHING_RESPONSE_ERROR = 'FETCHING_RESPONSE_ERROR';
export const FETCHING_RESPONSE_SUCCESS = 'FETCHING_RESPONSE_SUCCESS';
export const ADD_RESPONSE = 'ADD_RESPONSE';
export const ADD_MULTIPLE_RESPONSES = 'ADD_MULTIPLE_RESPONSES';
export const REMOVE_FETCHING = 'REMOVE_FETCHING';
export const UPDATING_RESPONSE_TEXT = 'UPDATING_RESPONSE_TEXT';

/* FEED CONSTANTS */
export const SETTING_FEED_LISTENER = 'SETTING_FEED_LISTENER';
export const SETTING_FEED_LISTENER_SUCCESS = 'SETTING_FEED_LISTENER_SUCCESS';
export const SETTING_FEED_LISTENER_ERROR = 'SETTING_FEED_LISTENER_ERROR';
export const ADD_NEW_RESPONSE_ID_TO_FEED = 'ADD_NEW_RESPONSE_ID_TO_FEED';
export const RESET_NEW_RESPONSES_AVAILABLE = 'RESET_NEW_RESPONSES_AVAILABLE';
